In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a1.size, a2.size

(3, 6)

In [5]:
a1.ndim, a2.ndim

(1, 2)

In [6]:
# Create a DataFrame from Numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

,0,1,2
0,1,2,3
1,4,5,6


## Creating Arrays

In [7]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [10]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 0, 8, 8, 8],
       [5, 2, 7, 6, 9],
       [7, 9, 7, 2, 6]])

In [11]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.31193014, 0.28096451, 0.05211877],
       [0.9601413 , 0.64524918, 0.91342862],
       [0.26472626, 0.49076662, 0.6354962 ],
       [0.09040428, 0.49391177, 0.9327536 ],
       [0.84233506, 0.78541115, 0.83697309]])

In [12]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.17411814, 0.58152375, 0.77186807],
       [0.08126176, 0.93237831, 0.98573703],
       [0.8878393 , 0.67423439, 0.97549011],
       [0.12658542, 0.29197926, 0.68230718],
       [0.57104457, 0.52416619, 0.76828217]])

In [13]:
np.unique(random_array)

array([0, 2, 5, 6, 7, 8, 9])

## Manipulating and Comparing Arrays

### Arithmetic

In [14]:
a1

array([1, 2, 3])

In [15]:
ones_1d = np.ones(3)
ones_1d

array([1., 1., 1.])

In [16]:
a1 + ones_1d

array([2., 3., 4.])

In [17]:
a1 - ones_1d

array([0., 1., 2.])

In [18]:
a1 * ones_1d

array([1., 2., 3.])

In [19]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [21]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [22]:
a3 = np.arange(1, 19).reshape(2, 3, 3)
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Aggregation

In [23]:
massive_array = np.random.random(100000) # 1d array of 100000 elements
np.sum(massive_array)

50147.76360769922

In [24]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.mean(a2)

3.5

In [26]:
np.std(a2)

1.707825127659933

### Demo of Std and Var

In [27]:
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [28]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [29]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [30]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)

## Reshaping & Transposing

### Reshaping

In [31]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

From numpy docs:
> When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when
>
> 1. they are equal, or
> 2. one of them is 1

In [34]:
a2_reshape * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

### Transposing

In [35]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

Helpful for matrix multiplication / dot product:

In [37]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

In [38]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [39]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [40]:
np.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Comparison Operators

In [41]:
a1

array([1, 2, 3])

In [42]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [44]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

## Sorting

In [45]:
random_ints = np.random.randint(10, size=(3, 5))
random_ints

array([[2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7]])

In [46]:
np.sort(random_ints)

array([[1, 2, 3, 3, 8],
       [0, 1, 3, 3, 7],
       [0, 4, 7, 9, 9]])

In [49]:
# Sorts index values
np.argsort(random_ints)

array([[3, 0, 1, 4, 2],
       [3, 4, 0, 1, 2],
       [2, 3, 4, 0, 1]])

## Images

In [51]:
from matplotlib.image import imread

panda = imread("numpy-images/panda.png")
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0